// Every ADC parameter, in one place. Drives both presentation/ADC_Parameters.pptx
// and the interactive app, so the two can never disagree.
//
// Slide kinds: title | section | param | table | recap | end
// A `param` slide is the workhorse: symbol and unit, a plain definition, the
// equation, a chart, an everyday analogy, a worked example, and why it matters.

const PARTS = [
  { id: 0, name: 'Opening', minutes: 4 },
  { id: 1, name: 'Part 1 · Resolution and the transfer function', minutes: 12 },
  { id: 2, name: 'Part 2 · Static accuracy (DC)', minutes: 16 },
  { id: 3, name: 'Part 3 · Dynamic performance (AC)', minutes: 20 },
  { id: 4, name: 'Part 4 · Speed and timing', minutes: 14 },
  { id: 5, name: 'Part 5 · Bandwidth and sampling', minutes: 10 },
  { id: 6, name: 'Part 6 · Power, interface and figures of merit', minutes: 8 },
  { id: 7, name: 'Part 7 · Architectures and the datasheet', minutes: 12 },
];

const SLIDES = [
  /* ============================================================ Opening */
  {
    id: 'title', kind: 'title', part: 0, minutes: 1,
    title: 'Inside the ADC',
    subtitle: 'Every parameter on the datasheet, and what it actually costs you',
    notes: 'This talk takes one component — the analog-to-digital converter — and walks through every number a datasheet quotes about it. '
      + 'Each parameter gets the same treatment: what it means in plain words, the equation, a picture, a real number, and what goes wrong when you ignore it.',
  },
  {
    id: 'what', kind: 'param', part: 0, minutes: 2,
    title: 'What an ADC does, in three steps',
    chart: 'blocks',
    what: 'An ADC turns a voltage into a number. It does it in three steps, repeated on every tick of a clock: hold the voltage still, compare it against a ruler with 2ᴺ marks, and write down the mark number in binary.',
    bullets: [
      'Sample and hold: freeze the input so it cannot move mid-measurement',
      'Quantise: decide which of the 2ᴺ levels the frozen voltage is nearest',
      'Encode: output that level as an N-bit binary word',
    ],
    analogy: 'Measuring a child’s height: ask them to stand still, line them up against a marked ruler, write the number in the book. Repeat every birthday.',
    example: { title: 'A 12-bit, 100 MSPS converter', lines: [
      '4096 marks on the ruler, one reading every 10 ns',
      'Output: 100 million 12-bit words per second = 1.2 Gbit/s',
      'Every parameter in this talk describes how well one of those three steps is done',
    ] },
    notes: 'Frame the whole talk: static parameters describe the ruler, dynamic parameters describe what happens when the input moves, and timing parameters describe the clock.',
  },
  {
    id: 'map', kind: 'map', part: 0, minutes: 1,
    title: 'The parameter map',
    what: 'Datasheet numbers fall into five families. Knowing which family a parameter belongs to tells you when it will bite you.',
    notes: 'Point at each family and say when it matters: static for DC measurement, dynamic for signals, timing for fast inputs, bandwidth for undersampling, power for the budget.',
  },

  /* ====================================== Part 1 · Resolution & transfer */
  { id: 'sec1', kind: 'section', part: 1, subtitle: 'How fine the ruler is, and what one step is worth', notes: 'The foundation: everything later is measured in LSBs.' },
  {
    id: 'resolution', kind: 'param', part: 1, minutes: 2,
    title: 'Resolution', symbol: 'N', unit: 'bits',
    what: 'How many binary digits the output word has. It fixes how many different levels the converter can report: 2ᴺ of them. It says nothing about how accurate those levels are — that is what every other parameter is for.',
    equations: [{ eq: 'number of levels = 2ᴺ', cap: '8 bits → 256 levels, 12 bits → 4096, 16 bits → 65 536' }],
    chart: 'resolution',
    analogy: 'The number of marks on a ruler. A ruler with millimetre marks is not automatically accurate — the marks could still be printed in the wrong places.',
    example: { title: 'Adding one bit', lines: [
      '12 bits: 4096 levels, step 488 µV over 2 V',
      '13 bits: 8192 levels, step 244 µV',
      'Each bit doubles the levels, halves the step, and buys about 6 dB',
    ] },
    matters: 'Resolution is the headline number and the most over-trusted one. A "16-bit" part delivering 12.5 effective bits is a 12.5-bit part.',
    typical: [['Audio', '16 – 24 bit'], ['Radio / SDR', '12 – 16 bit'], ['Oscilloscope', '8 – 12 bit'], ['Industrial sensing', '16 – 24 bit']],
  },
  {
    id: 'fsr', kind: 'param', part: 1, minutes: 2,
    title: 'Full-scale range', symbol: 'V_FS, FSR', unit: 'V',
    what: 'The span of input voltage between the lowest code and the highest. Drive the input outside it and the output clips: the top of the wave is flattened and the spectrum fills with harmonics that were never in the signal.',
    equations: [
      { eq: 'FSR = V_ref⁺ − V_ref⁻', cap: 'Often just V_ref, or 2 × V_ref for a differential input' },
      { eq: 'headroom (dBFS) = 20 log₁₀( V_in,pk / (FSR/2) )', cap: 'How far below full scale you are running' },
    ],
    chart: 'clipping',
    analogy: 'The length of the ruler. A 2-metre ruler cannot measure a 3-metre pole; it just reads "2 m" and you never learn the truth.',
    example: { title: 'Leaving headroom', lines: [
      'FSR 2 V peak-to-peak, so ±1 V',
      'Drive to ±0.9 V: 0.9 dB of back-off, no clipping',
      'Drive to ±1.2 V: clipped, and SFDR collapses from 80 dB to about 20 dB',
    ] },
    matters: 'Most in-the-field ADC failures are clipping, not noise. Radio front ends normally leave 6 to 12 dB of headroom for signal peaks.',
    typical: [['Differential high speed', '1 – 2 V pp'], ['Single-ended SAR', '0 – V_ref, 2.5 or 3.3 V'], ['Delta-sigma sensing', '±0.5 – ±5 V']],
  },
  {
    id: 'lsb', kind: 'param', part: 1, minutes: 2,
    title: 'LSB — the size of one step', symbol: 'q, LSB', unit: 'V',
    what: 'The voltage difference between two neighbouring codes. It is the natural unit for almost every other parameter on the datasheet: offset, DNL, INL and noise are all quoted in LSBs rather than volts, so they stay meaningful when the range changes.',
    equations: [{ eq: 'LSB = FSR / 2ᴺ', cap: 'The quantum: nothing smaller than this can be resolved' }],
    chart: 'staircase',
    analogy: 'The distance between two marks on the ruler. Everything else on the datasheet is measured in "how many marks wrong".',
    example: { title: 'Same converter, three ranges', lines: [
      '12 bit over 2 V: LSB = 2 / 4096 = 488 µV',
      '12 bit over 5 V: LSB = 1.22 mV',
      '16 bit over 2 V: LSB = 30.5 µV — smaller than most op-amp offsets',
    ] },
    matters: 'Once the LSB drops below the noise of the circuitry in front of the ADC, extra bits buy nothing at all.',
  },
  {
    id: 'qerror', kind: 'param', part: 1, minutes: 2,
    title: 'Quantisation error', symbol: 'e_q', unit: 'LSB',
    what: 'The difference between the real input and the level the ADC reported. Rounding to the nearest mark means the error is never more than half a step, and on a busy signal it is as often up as down — so we treat it as a small extra noise.',
    equations: [
      { eq: '−½ LSB ≤ e_q < +½ LSB', cap: 'The error can never exceed half a step' },
      { eq: 'σ² = LSB² / 12', cap: 'Noise power of a uniformly distributed error' },
    ],
    chart: 'qerror',
    analogy: 'Rounding every price to the nearest 10p. Sometimes you gain 5p, sometimes you lose 5p, and over a month it averages out like small random noise.',
    example: { title: '12-bit, 2 V range', lines: [
      'LSB 488 µV, so the error stays within ±244 µV',
      'rms error = 488 µV / √12 = 141 µV',
      'Against a 0.7 V rms full-scale sine that is 74 dB down',
    ] },
    expert: 'The uniform, white model breaks for very small or exactly periodic inputs, where the error becomes a deterministic pattern that shows up as spurs. Dither — deliberately adding a little noise before the quantiser — randomises it and restores the model.',
  },
  {
    id: 'coding', kind: 'param', part: 1, minutes: 2,
    title: 'Output coding', symbol: '—', unit: 'format',
    what: 'How the level number is written down in binary. It changes nothing about accuracy, but getting it wrong turns a clean sine into a waveform that jumps violently through mid-scale.',
    chart: 'coding',
    bullets: [
      'Straight binary: 0 … 2ᴺ−1, natural for unipolar inputs',
      'Offset binary: mid-scale is 1000…0, so zero volts is the middle code',
      'Two’s complement: offset binary with the top bit inverted; negative numbers are negative',
      'Gray code: only one bit changes between neighbours, so a mistimed read cannot produce a wildly wrong value',
    ],
    analogy: 'The same measurement written in different notations. "Minus three" and "3 below zero" are the same height; a reader expecting one and given the other gets nonsense.',
    example: { title: 'Mid-scale on a 12-bit part', lines: [
      'Straight binary: 2048 = 1000 0000 0000',
      'Two’s complement: 0 = 0000 0000 0000',
      'Read two’s complement as straight binary and every negative sample looks like a huge positive one',
    ] },
    matters: 'This is a five-minute bug that costs a day. Check the coding before you debug the analogue.',
  },
  {
    id: 'vref', kind: 'param', part: 1, minutes: 2,
    title: 'Reference voltage and its drift', symbol: 'V_ref, ppm/°C', unit: 'V, ppm/°C',
    what: 'Every ADC measures its input as a fraction of a reference. The converter can only ever be as accurate as that reference, so reference error appears directly as gain error, and reference drift appears as gain drift over temperature.',
    equations: [
      { eq: 'code ≈ 2ᴺ × V_in / V_ref', cap: 'The reading is a ratio, not an absolute measurement' },
      { eq: 'Δgain (ppm) = drift (ppm/°C) × ΔT', cap: 'A 10 ppm/°C reference over 50 °C moves gain by 500 ppm' },
    ],
    chart: 'vref',
    analogy: 'A ruler made of metal. It measures perfectly at 20 °C, but on a hot day the whole ruler has stretched and every reading is proportionally wrong.',
    example: { title: 'How many bits does drift cost?', lines: [
      '16-bit part: 1 LSB = 1/65 536 = 15 ppm of full scale',
      'A 10 ppm/°C reference over 50 °C drifts 500 ppm',
      'That is 33 LSB — five bits of accuracy lost to temperature alone',
    ] },
    matters: 'For any converter above 12 bits, the reference is usually the accuracy limit, not the converter. Noise on the reference also lands straight in the result.',
  },
  {
    id: 'recap1', kind: 'recap', part: 1, minutes: 1,
    title: 'Recap · the ruler itself',
    bullets: [
      'Resolution N sets the number of marks: 2ᴺ. It promises nothing about accuracy',
      'Full-scale range is the length of the ruler; going past it clips and sprays harmonics',
      'LSB = FSR / 2ᴺ is the unit every other parameter is quoted in',
      'Quantisation error is at most half an LSB and behaves like noise of power LSB²/12',
      'The reading is a ratio to V_ref, so reference error and drift are your error and drift',
    ],
  },

  /* ============================================ Part 2 · Static accuracy */
  { id: 'sec2', kind: 'section', part: 2, subtitle: 'Are the marks in the right places? The DC parameters', notes: 'These four — offset, gain, DNL, INL — describe the shape of the staircase.' },
  {
    id: 'offset', kind: 'param', part: 2, minutes: 2,
    title: 'Offset error', symbol: 'E_O', unit: 'LSB or mV',
    what: 'The whole staircase is shifted sideways: with zero volts in, the ADC does not report the zero code. Every reading is wrong by the same amount, in the same direction.',
    equations: [{ eq: 'E_O = (first actual transition) − (first ideal transition)', cap: 'Measured at the bottom of the range, in LSB' }],
    chart: 'offset',
    analogy: 'A bathroom scale that reads 2 kg with nobody standing on it. Every weight it reports is 2 kg too high, and you can fix it by turning the little wheel.',
    example: { title: 'A 5 LSB offset on a 12-bit, 2 V part', lines: [
      '5 × 488 µV = 2.44 mV added to every reading',
      'Measuring a 10 mV sensor signal: a 24 % error',
      'Measuring a 1 V signal: a 0.24 % error — the same offset, far less harm',
    ] },
    matters: 'Easy to remove: measure it once at zero input and subtract it in software. It matters most for small DC signals, and not at all for AC signals, where it only shifts bin 0 of the FFT.',
  },
  {
    id: 'gain', kind: 'param', part: 2, minutes: 2,
    title: 'Gain error', symbol: 'E_G', unit: '% FS or LSB',
    what: 'The staircase has the right starting point but the wrong slope, so the error grows the further up the range you go. Usually the reference is the culprit.',
    equations: [{ eq: 'E_G = (actual slope / ideal slope) − 1', cap: 'Quoted as a percentage of full scale, or in LSB at full scale' }],
    chart: 'gain',
    analogy: 'A tailor’s tape measure that has stretched. It still starts at zero, but by the far end everything reads short by a fixed proportion.',
    example: { title: '0.5 % gain error, 12-bit', lines: [
      'At mid-scale (2048): error 10 LSB',
      'At full scale (4095): error 20 LSB',
      'At zero: no error at all — that is what distinguishes it from offset',
    ] },
    matters: 'Also correctable in software with a two-point calibration: measure near zero and near full scale, then fit a straight line. What calibration cannot fix is drift.',
  },
  {
    id: 'dnl', kind: 'param', part: 2, minutes: 3,
    title: 'DNL — differential non-linearity', symbol: 'DNL', unit: 'LSB',
    what: 'How much wider or narrower each individual step is than one ideal LSB. It is a local measure: one bad step among 4095 good ones still counts.',
    equations: [{ eq: 'DNL(k) = (actual width of code k) / LSB − 1', cap: 'Zero means every step is exactly one LSB wide' }],
    chart: 'dnl',
    analogy: 'A ruler where the marks are not evenly spaced. Most centimetres are right, but one is 1.4 cm and the next is 0.6 cm.',
    example: { title: 'Reading the spec', lines: [
      'DNL = ±0.5 LSB: every step is between 0.5 and 1.5 LSB wide',
      'DNL = −0.9 LSB: one step is only a tenth of an LSB wide — nearly invisible',
      'DNL = −1.0 LSB: that code never appears at all (see the next slide)',
    ] },
    matters: 'DNL is the noise-like part of static error: it adds directly to the noise floor and generates spurs, so it hurts AC performance as well as DC.',
    typical: [['Good SAR', '±0.5 LSB'], ['Good pipeline', '±0.3 LSB'], ['Delta-sigma', '±0.05 LSB']],
  },
  {
    id: 'missing', kind: 'param', part: 2, minutes: 2,
    title: 'Missing codes and monotonicity', symbol: '—', unit: 'pass / fail',
    what: 'Two guarantees that follow from DNL. A code is missing when DNL reaches −1 LSB: that output value can never occur, whatever the input. A converter is monotonic when a rising input can never produce a falling output.',
    equations: [
      { eq: 'DNL ≤ −1 LSB  →  missing code', cap: 'The step has been squeezed to zero width' },
      { eq: 'DNL > −1 LSB everywhere  →  guaranteed monotonic', cap: 'The usual way the guarantee is stated' },
    ],
    chart: 'missing',
    analogy: 'A lift that never stops on the fourth floor. It works fine, but you can never get out there — and if it sometimes goes down when you press "up", nothing built on it can be trusted.',
    example: { title: 'Why monotonicity is non-negotiable in a control loop', lines: [
      'A servo raises its drive and reads the sensor back',
      'A non-monotonic ADC reports a fall, so the loop pushes harder',
      'The loop latches up or oscillates — the classic symptom of a non-monotonic converter',
    ] },
    matters: '"No missing codes" is a guarantee worth paying for in measurement work. "Monotonic" is essential in any feedback loop.',
  },
  {
    id: 'inl', kind: 'param', part: 2, minutes: 3,
    title: 'INL — integral non-linearity', symbol: 'INL', unit: 'LSB',
    what: 'How far the whole staircase bends away from a straight line, once offset and gain have been taken out. Where DNL is local and jagged, INL is the smooth, long bow across the range — and it is the running sum of DNL.',
    equations: [
      { eq: 'INL(k) = Σ DNL up to k', cap: 'Accumulated step errors' },
      { eq: 'INL = (actual transition − ideal) / LSB', cap: 'Endpoint method; the best-fit-line method gives about half the number' },
    ],
    chart: 'inl',
    analogy: 'A ruler that is gently bowed. Each individual centimetre looks fine, but by the middle the accumulated bend has you several millimetres out.',
    example: { title: 'INL is what limits distortion', lines: [
      '±2 LSB INL on a 14-bit part',
      'The bow acts like a soft nonlinearity, so it makes harmonics',
      'Typically caps SFDR around 80 – 85 dB no matter how good the noise is',
    ] },
    matters: 'INL sets the distortion floor. If you need SFDR, buy INL. Note which definition the datasheet uses: endpoint or best-fit changes the number by a factor of two.',
    expert: 'Bowed INL (an even-order shape) produces mostly HD2; S-shaped INL (odd-order) produces mostly HD3. The shape of the INL plot predicts which harmonic will dominate the spectrum.',
  },
  {
    id: 'tue', kind: 'param', part: 2, minutes: 2,
    title: 'Total unadjusted error', symbol: 'TUE', unit: 'LSB',
    what: 'The single worst-case number: every static error added together, with no calibration applied. It answers the only question that matters for an uncalibrated system — how far out can one reading possibly be?',
    equations: [
      { eq: 'TUE ≈ √( E_O² + E_G² + INL² + … )', cap: 'Root-sum-square, if the errors are independent' },
      { eq: 'TUE_worst = |E_O| + |E_G| + |INL| + ½', cap: 'Straight sum: the pessimistic bound some datasheets quote' },
    ],
    chart: 'tue',
    analogy: 'Every source of measurement error in one number, the way a shipping estimate quotes the worst case rather than the average.',
    example: { title: '12-bit part, no calibration', lines: [
      'Offset 2 LSB, gain 3 LSB, INL 1.5 LSB, quantisation 0.5 LSB',
      'Root-sum-square: √(4 + 9 + 2.25 + 0.25) = 3.9 LSB',
      'Worst case sum: 7 LSB — so trust about 9 of your 12 bits',
    ] },
    matters: 'If you never calibrate, TUE is the only accuracy number that means anything. If you do calibrate, offset and gain drop out and INL plus drift dominate.',
  },
  {
    id: 'drift', kind: 'param', part: 2, minutes: 2,
    title: 'Temperature drift', symbol: 'ppm/°C', unit: 'ppm/°C or LSB/°C',
    what: 'Offset and gain both move with temperature. Calibration at 25 °C on the bench does nothing for a board that runs at 70 °C in a cabinet, so drift is the error that survives calibration.',
    equations: [{ eq: 'error(T) = error(25 °C) + drift × (T − 25)', cap: '1 ppm of full scale = 0.065 LSB at 16 bits' }],
    chart: 'drift',
    analogy: 'Calibrating your kitchen scale in a cold kitchen, then using it beside a hot oven. The calibration was honest; the conditions moved.',
    example: { title: 'A 16-bit measurement over an industrial range', lines: [
      'Gain drift 5 ppm/°C, range −40 to +85 °C, so ΔT = 60 °C from calibration',
      '5 × 60 = 300 ppm = 19.7 LSB at 16 bits',
      'Four bits gone, and no amount of room-temperature calibration recovers them',
    ] },
    matters: 'For precision work, drift and reference stability usually beat resolution as the thing to spend money on.',
  },
  {
    id: 'psrr', kind: 'param', part: 2, minutes: 2,
    title: 'PSRR and CMRR', symbol: 'PSRR, CMRR', unit: 'dB',
    what: 'Two rejection ratios. PSRR says how much of a wobble on the supply rail leaks into the reading. CMRR says how much of a voltage common to both inputs of a differential converter leaks in, when in theory only the difference should count.',
    equations: [
      { eq: 'PSRR = 20 log₁₀( ΔV_supply / ΔV_error )', cap: 'Higher is better' },
      { eq: 'CMRR = 20 log₁₀( ΔV_common / ΔV_error )', cap: 'Differential inputs only' },
    ],
    chart: 'psrr',
    analogy: 'Trying to weigh something on a scale sitting on a washing machine. CMRR is how well the scale ignores the shaking; PSRR is how well it ignores a flickering mains supply.',
    example: { title: 'Supply ripple leaking in', lines: [
      'Switching regulator ripple: 20 mV at 500 kHz',
      'ADC PSRR at 500 kHz: 60 dB → divide by 1000',
      '20 µV of error — about 0.7 LSB on a 16-bit, 2 V part, and it shows as a spur at 500 kHz',
    ] },
    matters: 'PSRR falls with frequency, so the number at DC is the flattering one. Check it at your switching regulator’s frequency.',
  },
  {
    id: 'recap2', kind: 'recap', part: 2, minutes: 1,
    title: 'Recap · static accuracy',
    bullets: [
      'Offset: the staircase is shifted — same error everywhere, easy to calibrate out',
      'Gain: the staircase has the wrong slope — error grows with signal, two-point calibration fixes it',
      'DNL: each step the wrong width. At −1 LSB a code goes missing; above −1 everywhere means monotonic',
      'INL: the whole curve bows. It is the running sum of DNL, and it sets your distortion floor',
      'TUE bundles them all for an uncalibrated system; drift is what survives calibration',
    ],
  },

  /* =========================================== Part 3 · Dynamic (AC) */
  { id: 'sec3', kind: 'section', part: 3, subtitle: 'What happens once the input starts moving', notes: 'These are all measured the same way: apply a pure sine, take an FFT, and read the answer off the spectrum.' },
  {
    id: 'snr', kind: 'param', part: 3, minutes: 3,
    title: 'SNR — signal-to-noise ratio', symbol: 'SNR', unit: 'dB',
    what: 'How far the wanted tone stands above the noise, with the harmonics deliberately excluded. It is the parameter that tells you how small a signal you can still see.',
    equations: [
      { eq: 'SNR = 10 log₁₀( P_signal / P_noise )', cap: 'Harmonics are removed from the noise sum first' },
      { eq: 'SNR_ideal = 6.02 N + 1.76 dB', cap: 'The best a perfect N-bit converter can manage' },
    ],
    chart: 'snr',
    analogy: 'How loudly a voice stands out over the hiss of a room. Distortion is a separate problem — that is the voice being slurred, not drowned.',
    example: { title: 'Where the ideal number comes from', lines: [
      'Full-scale sine power: (FSR/2)²/2 = FSR²/8',
      'Quantisation noise power: LSB²/12 = FSR²/(12 × 2²ᴺ)',
      'Ratio = 1.5 × 2²ᴺ → 10 log₁₀ = 6.02 N + 1.76 dB',
    ] },
    matters: 'Real SNR sits below the ideal because of thermal noise, clock jitter and DNL. The gap between them is the honest measure of an ADC’s quality.',
  },
  {
    id: 'inoise', kind: 'param', part: 3, minutes: 3,
    title: 'Input-referred noise and noise-free bits', symbol: 'σ_n, NFR', unit: 'LSB rms, bits',
    what: 'Short the input and take thousands of readings: a perfect ADC returns the same code every time, a real one returns a small spread of codes. The width of that spread is input-referred noise, and it decides how many of your bits are actually trustworthy.',
    equations: [
      { eq: 'noise-free bits = log₂( 2ᴺ / (6.6 × σ_n) )', cap: 'Peak-to-peak: codes that never flicker' },
      { eq: 'effective resolution = log₂( 2ᴺ / σ_n )', cap: 'The rms version, about 2.7 bits more generous' },
    ],
    chart: 'histogram',
    analogy: 'A bathroom scale whose last digit will not settle. It may display grams, but if that digit dances over five values, you do not have gram resolution.',
    example: { title: 'A 24-bit delta-sigma part', lines: [
      'Input-referred noise: 12 LSB rms',
      'Noise-free bits = log₂(16 777 216 / 79) = 17.7',
      'The other 6 bits are real outputs, but they only ever show noise',
    ] },
    matters: 'This is why 24-bit converters are never 24-bit measurements. Datasheets often give a table of noise-free bits against output rate — that table is the honest specification.',
  },
  {
    id: 'thd', kind: 'param', part: 3, minutes: 3,
    title: 'THD and the individual harmonics', symbol: 'THD, HD2, HD3', unit: 'dBc or %',
    what: 'A perfect converter fed one pure tone returns one pure tone. A real one bends the signal slightly, and the bend creates copies at exact multiples of the input frequency. THD adds up all those copies; HD2 and HD3 name the two that usually dominate.',
    equations: [
      { eq: 'THD = 10 log₁₀( (P₂ + P₃ + … + P₉) / P₁ )', cap: 'Quoted in dBc: decibels relative to the carrier' },
      { eq: 'THD(%) = 100 × √( ΣP_h / P₁ )', cap: 'The same thing as a percentage' },
    ],
    chart: 'thd',
    analogy: 'A slightly buzzy loudspeaker. Play one clean note and you also hear faint notes an octave and an octave-and-a-fifth above it, which the recording never contained.',
    example: { title: 'Reading a spectrum', lines: [
      'Tone at 10 MHz, 0 dBFS. HD2 appears at 20 MHz, −72 dBc',
      'HD3 at 30 MHz, −78 dBc',
      'THD = 10 log₁₀(10⁻⁷·² + 10⁻⁷·⁸) = −70.9 dBc',
    ] },
    matters: 'Harmonics fold. A harmonic above f_s/2 comes back inside the band at a frequency that looks like a real signal, which is why a distortion problem often presents as a mystery spur.',
    expert: 'Even harmonics come mainly from asymmetry between the two halves of a differential path; odd harmonics from symmetric compression. HD2 that improves when you balance the driver, and HD3 that worsens with amplitude, are the classic signatures.',
  },
  {
    id: 'sinad', kind: 'param', part: 3, minutes: 2,
    title: 'SINAD — signal to noise and distortion', symbol: 'SINAD, SNDR', unit: 'dB',
    what: 'The honest one. SNR ignores harmonics, THD ignores noise; SINAD counts everything that is not the wanted tone. It is the number ENOB is calculated from.',
    equations: [{ eq: 'SINAD = 10 log₁₀( P_signal / (P_noise + P_distortion) )', cap: 'Always the smallest of the three ratios' }],
    chart: 'sinad',
    analogy: 'Judging a phone call by how much of it you actually understood, rather than measuring the hiss and the crackle separately.',
    example: { title: 'Combining the two', lines: [
      'SNR 72 dB, THD −76 dBc',
      'SINAD = −10 log₁₀(10⁻⁷·² + 10⁻⁷·⁶) = 70.5 dB',
      'The worse of the two dominates: fixing distortion alone would gain only 1.5 dB',
    ] },
    matters: 'When a datasheet quotes SNR and SINAD close together, the part is noise-limited. When SINAD is far below SNR, it is distortion-limited — and the fix is a different one.',
  },
  {
    id: 'enob', kind: 'param', part: 3, minutes: 3,
    title: 'ENOB — effective number of bits', symbol: 'ENOB', unit: 'bits',
    what: 'The resolution you actually got, obtained by running the ideal-SNR formula backwards on the measured SINAD. It converts a decibel figure into the only unit people intuitively understand: bits.',
    equations: [
      { eq: 'ENOB = ( SINAD − 1.76 ) / 6.02', cap: 'For a full-scale input' },
      { eq: 'ENOB = ( SINAD − 1.76 + back-off ) / 6.02', cap: 'Add the dB you backed off, or you will under-report the part' },
    ],
    chart: 'enob',
    analogy: 'A car’s advertised top speed against the speed it reaches on a real road with a real load. ENOB is the road figure.',
    example: { title: 'A "14-bit" converter at 70 MHz input', lines: [
      'Measured SINAD: 68 dB, driven 1 dB below full scale',
      'ENOB = (68 − 1.76 + 1) / 6.02 = 11.2 bits',
      'Nearly three bits of the fourteen are not there at this frequency',
    ] },
    matters: 'ENOB always falls as input frequency rises. A single ENOB number is meaningless without the frequency it was measured at.',
  },
  {
    id: 'sfdr', kind: 'param', part: 3, minutes: 3,
    title: 'SFDR — spurious-free dynamic range', symbol: 'SFDR', unit: 'dBc or dBFS',
    what: 'The gap between the wanted tone and the single largest unwanted spike anywhere in the spectrum, whether or not it is a harmonic. It answers one question exactly: how small a signal can I still find while a big one is present?',
    equations: [{ eq: 'SFDR = 10 log₁₀( P_signal / P_largest spur )', cap: 'dBc relative to the carrier, or dBFS relative to full scale' }],
    chart: 'sfdr',
    analogy: 'Trying to hear a whisper at a party while someone shouts. SFDR is how much quieter than the shout a whisper can be and still be picked out.',
    example: { title: 'Why a radio receiver lives on SFDR', lines: [
      'Wanted channel at −90 dBFS, a strong neighbour at −10 dBFS',
      'You need 80 dB of SFDR just to see the wanted channel at all',
      'A spur at −70 dBc from the strong signal would completely mask it',
    ] },
    matters: 'SFDR is the number radio engineers care about most, and it is often limited by INL rather than by noise. Averaging improves the noise floor but never improves SFDR.',
  },
  {
    id: 'imd', kind: 'param', part: 3, minutes: 2,
    title: 'Intermodulation distortion', symbol: 'IMD2, IMD3, IP3', unit: 'dBc',
    what: 'Feed two tones instead of one and the nonlinearity mixes them together, producing sums and differences. The third-order products at 2f₁−f₂ and 2f₂−f₁ are the dangerous ones because they land right next to the originals, where no filter can remove them.',
    equations: [
      { eq: 'second order: f₂ ± f₁', cap: 'Usually far away and filterable' },
      { eq: 'third order: 2f₁ − f₂ and 2f₂ − f₁', cap: 'Falls in-band, right beside the wanted tones' },
    ],
    chart: 'imd',
    analogy: 'Two singers slightly out of tune producing an audible beat note that neither of them is singing.',
    example: { title: 'Two carriers 1 MHz apart', lines: [
      'Tones at 10.0 and 11.0 MHz',
      'Third-order products at 9.0 and 12.0 MHz — inside the same channel',
      'At −75 dBc they set the floor for any weak signal nearby',
    ] },
    matters: 'Single-tone THD can look excellent while two-tone IMD is poor. Any receiver that must handle more than one signal at once should be specified on IMD, not THD.',
  },
  {
    id: 'floor', kind: 'param', part: 3, minutes: 2,
    title: 'FFT noise floor and processing gain', symbol: '—', unit: 'dBFS',
    what: 'The noise floor you see on an FFT plot is not the converter’s SNR. The total noise is spread across N/2 bins, so each bin holds only a fraction of it. Taking a longer transform pushes the visible floor down without the converter improving at all.',
    equations: [
      { eq: 'floor = −SNR − 10 log₁₀( N/2 )', cap: 'Per-bin level, in dBFS' },
      { eq: 'processing gain = 10 log₁₀( N/2 )', cap: '27 dB for a 1024-point FFT' },
    ],
    chart: 'floor',
    analogy: 'Spreading a fixed amount of butter over more and more slices of bread. There is no more butter; each slice just gets less.',
    example: { title: '12-bit part, 4096-point FFT', lines: [
      'SNR 74 dB, processing gain 10 log₁₀(2048) = 33 dB',
      'Visible floor: −107 dBFS',
      'Change to a 256-point FFT and the same converter shows −95 dBFS',
    ] },
    matters: 'Never compare noise floors from FFTs of different lengths. This is the most common way ADC plots are made to look better than they are.',
  },
  {
    id: 'dynrange', kind: 'param', part: 3, minutes: 2,
    title: 'Dynamic range', symbol: 'DR', unit: 'dB',
    what: 'The span between the largest signal the converter can take without clipping and the smallest it can still distinguish from noise. It is what decides whether you need an automatic gain control in front of it.',
    equations: [{ eq: 'DR = 20 log₁₀( largest / smallest )', cap: 'For a converter with no oversampling, DR ≈ SNR' }],
    chart: 'dynrange',
    analogy: 'A camera photographing a room with a bright window. Dynamic range is whether you can see detail in the sunlit street and in the shadowy corner in one shot.',
    example: { title: 'Wi-Fi receiver', lines: [
      'Strongest signal at the ADC: −10 dBFS. Weakest wanted: −80 dBFS',
      'Needs 70 dB of usable range, so a 12-bit part with 74 dB SNR just fits',
      'Add a 20 dB fade margin and you need 14 bits, or an AGC',
    ] },
    matters: 'Oversampling buys dynamic range that resolution alone does not: every doubling of the sample rate adds 3 dB, and a noise-shaping loop adds far more.',
  },
  {
    id: 'recap3', kind: 'recap', part: 3, minutes: 1,
    title: 'Recap · dynamic performance',
    bullets: [
      'SNR: tone above the noise, harmonics excluded. Ideal is 6.02 N + 1.76 dB',
      'THD: all the harmonics added up; HD2 and HD3 usually dominate',
      'SINAD counts noise and distortion together — it is the honest one',
      'ENOB = (SINAD − 1.76 + back-off) / 6.02, and it always falls with input frequency',
      'SFDR is the biggest single spur: the number that decides if you can see a weak signal beside a strong one',
      'The FFT floor is not the SNR — subtract the processing gain of 10 log₁₀(N/2)',
    ],
  },

  /* ============================================ Part 4 · Speed & timing */
  { id: 'sec4', kind: 'section', part: 4, subtitle: 'The clock, and everything that has to finish before the next tick', notes: 'Timing parameters are the ones that silently destroy a high-frequency measurement.' },
  {
    id: 'fs', kind: 'param', part: 4, minutes: 2,
    title: 'Sampling rate and throughput', symbol: 'f_s', unit: 'SPS',
    what: 'How many complete conversions the ADC delivers per second. Nyquist sets the floor: you must sample faster than twice the highest frequency present, or fast signals come back disguised as slow ones and no processing can undo it.',
    equations: [
      { eq: 'f_s > 2 × f_max', cap: 'Nyquist. In practice 2.2 to 2.5×, to leave the anti-alias filter room' },
      { eq: 'f_alias = | f − k f_s |', cap: 'Where a too-fast tone reappears' },
    ],
    chart: 'aliasing',
    analogy: 'A film camera at 24 frames a second. Spokes on a wheel spinning faster than that appear to turn backwards, and the footage cannot be repaired afterwards.',
    example: { title: 'A 60 MHz tone at 100 MSPS', lines: [
      'Nyquist limit: 50 MHz',
      'The tone appears at |60 − 100| = 40 MHz',
      'It looks exactly like a genuine 40 MHz signal — nothing marks it as fake',
    ] },
    matters: 'Multiplexed converters share one core between channels, so the per-channel rate is the throughput divided by the channel count. Check which number the datasheet quotes.',
  },
  {
    id: 'latency', kind: 'param', part: 4, minutes: 2,
    title: 'Conversion time and latency', symbol: 't_conv, latency', unit: 's, cycles',
    what: 'Two different things that are easy to confuse. Conversion time is how long one measurement takes. Latency is how long you wait before that particular sample appears at the output — in a pipeline converter, several samples are in flight at once.',
    equations: [{ eq: 'throughput = 1 / t_conv, but latency may be many cycles', cap: 'A pipeline delivers a sample every cycle, each one several cycles old' }],
    chart: 'latency',
    analogy: 'A car factory rolls out one car a minute, but any individual car spent eight hours on the line. Throughput and latency are not the same measurement.',
    example: { title: 'Architecture decides latency', lines: [
      'SAR: N clock cycles, result available immediately after — latency ≈ 0',
      'Pipeline: one result per clock, but 8 to 16 cycles behind the input',
      'Delta-sigma: hundreds of cycles, because of the decimation filter',
    ] },
    matters: 'Latency is irrelevant for spectrum analysis and fatal in a fast control loop, where it becomes phase lag and eats your stability margin.',
  },
  {
    id: 'aperture', kind: 'param', part: 4, minutes: 2,
    title: 'Aperture delay', symbol: 't_AD', unit: 's',
    what: 'The fixed gap between the clock edge arriving and the sampling switch actually opening. Because it is fixed and repeatable, it is harmless in a single converter — it just shifts the time axis slightly.',
    equations: [{ eq: 'sample instant = clock edge + t_AD', cap: 'Constant, and therefore calibratable' }],
    chart: 'apdelay',
    analogy: 'A camera with a shutter that always fires exactly 20 ms after you press the button. Predictable, so you simply press 20 ms early.',
    example: { title: 'When it does matter', lines: [
      'Two ADCs interleaved to double the rate must sample exactly half a period apart',
      'A 200 ps aperture-delay mismatch at 500 MSPS is a 10 % timing error',
      'The result is an interleaving spur at f_s/2 − f_in',
    ] },
    matters: 'Fixed delay is fine. Mismatch between channels is not — it is the main reason interleaved converters need calibration.',
  },
  {
    id: 'jitter', kind: 'param', part: 4, minutes: 3,
    title: 'Aperture jitter', symbol: 't_j', unit: 's rms',
    what: 'The random, cycle-to-cycle variation in when the switch opens. A fast-moving input travels a long way during that uncertainty, so the frozen value is wrong. Above a certain input frequency, jitter — not resolution — sets your accuracy.',
    equations: [
      { eq: 'SNR_jitter = −20 log₁₀( 2π f_in t_j )', cap: 'Depends on the input frequency, not the sample rate' },
      { eq: 'ΔV = (dV/dt) × t_j', cap: 'Where it comes from: slope times timing error' },
    ],
    chart: 'jitter',
    analogy: 'Photographing a sprinter with a shutter that fires a little early or late each time. The faster the runner, the more the same timing slip blurs the picture.',
    example: { title: 'The budget at 200 MHz', lines: [
      '1 ps rms jitter: SNR limit = −20 log₁₀(2π × 2e8 × 1e−12) = 58 dB',
      'That caps you at 9.3 effective bits, whatever the part claims',
      'For 12 bits at 200 MHz you need about 160 fs — total, clock plus converter',
    ] },
    matters: 'Jitter comes from the clock source as much as the ADC. Undersampling a high IF is exactly the case where jitter dominates, because the formula uses the input frequency.',
    expert: 'Total jitter is the root-sum-square of the converter’s own aperture jitter and the clock’s integrated phase noise over the relevant offset band. Halving one when the other dominates buys nothing.',
  },
  {
    id: 'acq', kind: 'param', part: 4, minutes: 3,
    title: 'Acquisition and settling time', symbol: 't_acq, t_s', unit: 's',
    what: 'During the track phase the hold capacitor has to charge to within half an LSB of the input. More bits means a tighter target and therefore more time constants — and this is what sets the demands on whatever amplifier drives the converter.',
    equations: [
      { eq: 'error = FSR × e^(−t/τ)', cap: 'Single-pole settling' },
      { eq: 'number of τ = ln( 2^(N+1) )', cap: '9.0 τ for 12 bits, 11.8 τ for 16 bits' },
    ],
    chart: 'settling',
    analogy: 'Filling a measuring jug from a tap. Getting roughly full is quick; getting to the exact line, with the surface completely still, takes far longer.',
    example: { title: 'Driving a 16-bit SAR at 1 MSPS', lines: [
      'Track time available: about 500 ns',
      '16 bits needs 11.8 time constants, so τ < 42 ns',
      'That means an amplifier bandwidth above 3.8 MHz, settling to 0.0008 % — not a casual op-amp',
    ] },
    matters: 'Under-settling looks exactly like distortion in the FFT, because the error depends on how far the input moved. Most "the ADC is bad" reports are really driver settling.',
  },
  {
    id: 'slew', kind: 'param', part: 4, minutes: 2,
    title: 'Slew rate and overvoltage recovery', symbol: 'SR, t_rec', unit: 'V/µs, s',
    what: 'Slew rate is how fast the driving circuit can move its output; if the signal demands more, the peaks are flattened and the spectrum fills with harmonics. Overvoltage recovery is how long the input takes to behave again after being driven past full scale.',
    equations: [
      { eq: 'SR_needed = π × FSR × f', cap: 'Peak slope of a full-scale sine' },
      { eq: 'recovery: input returns to spec within t_rec', cap: 'Typically tens of nanoseconds to microseconds' },
    ],
    chart: 'slew',
    analogy: 'A speedometer needle that cannot swing fast enough. Slam the accelerator and it lags, so the trace you record is a flattened version of what really happened.',
    example: { title: 'A 2 V range at 50 MHz', lines: [
      'SR needed = π × 2 × 50e6 = 314 V/µs',
      'A 100 V/µs op-amp will visibly flatten the peaks',
      'The FFT shows this as HD3 rising steeply with amplitude',
    ] },
    matters: 'Overvoltage recovery matters in radar and pulsed systems, where a huge blocking signal is followed immediately by the tiny echo you actually want.',
  },
  {
    id: 'recap4', kind: 'recap', part: 4, minutes: 1,
    title: 'Recap · speed and timing',
    bullets: [
      'f_s must exceed 2 × the highest frequency present, or tones fold and cannot be recovered',
      'Conversion time is not latency: a pipeline gives one result per clock, each many clocks old',
      'Aperture delay is fixed and harmless; mismatch between interleaved channels is not',
      'Aperture jitter limits SNR to −20 log₁₀(2π f_in t_j) — set by input frequency, not sample rate',
      'Settling to N bits needs ln(2^(N+1)) time constants; under-settling looks exactly like distortion',
    ],
  },

  /* ============================================= Part 5 · Bandwidth */
  { id: 'sec5', kind: 'section', part: 5, subtitle: 'What the input can accept, and what the clock can keep up with', notes: 'Analog bandwidth and sample rate are separate specifications, and undersampling depends on the gap between them.' },
  {
    id: 'bw', kind: 'param', part: 5, minutes: 2,
    title: 'Analog input bandwidth', symbol: 'BW₋₃dB', unit: 'Hz',
    what: 'How high in frequency the sample-and-hold front end will still faithfully follow the input, measured where the response has fallen 3 dB. It is completely independent of the sample rate, and it is often several times higher.',
    equations: [{ eq: 'BW₋₃dB = 1 / (2π τ)', cap: 'Set by the input switch resistance and hold capacitance' }],
    chart: 'bandwidth',
    analogy: 'How high a note a microphone can pick up, which is a different question from how many times a second you write the level down.',
    example: { title: 'A typical high-speed part', lines: [
      'Sample rate 250 MSPS, so Nyquist is 125 MHz',
      'Analog bandwidth 900 MHz — more than seven times higher',
      'That headroom is what makes undersampling a 400 MHz IF possible',
    ] },
    matters: 'A wide input bandwidth also lets in wideband noise and out-of-band interference, so the anti-alias filter has to do more work, not less.',
  },
  {
    id: 'fpbw', kind: 'param', part: 5, minutes: 2,
    title: 'Full-power and full-linear bandwidth', symbol: 'FPBW, FLBW', unit: 'Hz',
    what: 'Two more honest bandwidth numbers. Full-power bandwidth is where a full-scale input has dropped 3 dB. Full-linear bandwidth is the much lower frequency up to which the converter still meets its distortion specification — and that is the one you can actually use.',
    equations: [{ eq: 'FLBW < FPBW < BW_small-signal', cap: 'Almost always in that order' }],
    chart: 'fpbw',
    analogy: 'A car’s top speed against the speed at which it still handles safely. The brochure quotes one; you drive at the other.',
    example: { title: 'The gap is large', lines: [
      'Small-signal bandwidth: 900 MHz',
      'Full-power bandwidth: 500 MHz',
      'Full-linear bandwidth (SFDR still above 70 dB): 200 MHz',
    ] },
    matters: 'Never design to the headline bandwidth. Find the frequency at which ENOB and SFDR are still adequate, and treat that as the real limit.',
  },
  {
    id: 'undersample', kind: 'param', part: 5, minutes: 3,
    title: 'Undersampling and bandpass sampling', symbol: '—', unit: '—',
    what: 'Aliasing used deliberately. A signal in a narrow band high up in frequency can be sampled far below its own frequency: it folds down into the first Nyquist zone intact, with the ADC doing the work of a mixer.',
    equations: [
      { eq: '2 f_H / n ≤ f_s ≤ 2 f_L / (n − 1)', cap: 'Keeps the band [f_L, f_H] clear of the fold points' },
      { eq: 'requires BW_analog > f_H', cap: 'The front end must genuinely reach the real frequency' },
    ],
    chart: 'zones',
    analogy: 'Watching a fast fan under a strobe light tuned so the blades appear to creep slowly. Nothing about the fan changed; you chose a look rate that makes it easy to watch.',
    example: { title: 'A 70 MHz IF at 61.44 MSPS', lines: [
      'The band 65 – 75 MHz folds into the second Nyquist zone',
      'It folds down to |70 − 61.44| = 8.56 MHz, orientation intact (zone 3 is odd)',
      'Needs a sharp bandpass filter and very low jitter, because 70 MHz sets the jitter budget',
    ] },
    matters: 'The jitter penalty is set by the real input frequency, not the sample rate. Undersampling a high IF is the hardest thing you can ask of a sampling clock.',
  },
  {
    id: 'osr', kind: 'param', part: 5, minutes: 3,
    title: 'Oversampling ratio and decimation', symbol: 'OSR', unit: '×',
    what: 'Sampling much faster than Nyquist spreads the same fixed quantisation noise over a wider band. A digital filter then keeps only the band you care about and throws the rest away — taking most of the noise with it.',
    equations: [
      { eq: 'OSR = f_s / (2 × BW)', cap: 'How many times faster than strictly necessary' },
      { eq: 'gain = 10 log₁₀(OSR)', cap: '+3 dB per doubling, plain oversampling' },
      { eq: 'L-th order shaping: (6L + 3) dB per doubling', cap: '+9 dB first order, +15 dB second order' },
    ],
    chart: 'osr',
    analogy: 'Weighing a letter on a coarse scale a thousand times while nudging it, then averaging. Many rough measurements, carefully combined, beat one careful measurement.',
    example: { title: 'A 24-bit audio converter', lines: [
      '1-bit modulator at 6.1 MSPS, signal band 20 kHz → OSR = 153',
      'Seven doublings with second-order shaping: 7 × 15 = 105 dB gained',
      'A one-bit front end ends up delivering about 20 real bits',
    ] },
    matters: 'This is the whole trick behind delta-sigma converters, and it is why they can be extremely accurate and quite slow at the same time.',
  },

  /* ================================ Part 6 · Power, interface, figures of merit */
  { id: 'sec6', kind: 'section', part: 6, subtitle: 'What it costs, how you get the data out, and how to compare parts fairly', notes: 'The commercial half of the datasheet.' },
  {
    id: 'power', kind: 'param', part: 6, minutes: 2,
    title: 'Power dissipation and supplies', symbol: 'P_D', unit: 'W',
    what: 'What the converter costs you in watts, usually split across an analogue supply, a digital supply and an I/O supply. It scales roughly with sample rate, and very steeply with resolution — every extra bit costs about four times the power.',
    equations: [{ eq: 'P ∝ f_s × 2²ᴺᵒᵇ', cap: 'Why 16 bits at 1 GSPS is so much harder than 8 bits at 1 GSPS' }],
    chart: 'power',
    analogy: 'Precision costs energy everywhere: a laboratory balance uses far more power than a kitchen scale, for the same reason.',
    example: { title: 'Comparing two parts', lines: [
      '12 bit, 100 MSPS: 300 mW → 3 nJ per conversion',
      '16 bit, 100 MSPS: 1.4 W → 14 nJ per conversion',
      'Many parts offer a low-power mode that trades sample rate for milliwatts',
    ] },
    matters: 'In battery and multi-channel systems, energy per conversion matters more than the headline power figure — which is exactly what the next two slides measure.',
  },
  {
    id: 'walden', kind: 'param', part: 6, minutes: 2,
    title: 'Walden figure of merit', symbol: 'FoM_W', unit: 'J/conversion-step',
    what: 'Energy spent for each conversion, divided by the number of levels actually resolved. It lets you compare a slow precision part against a fast coarse one on equal terms. Lower is better.',
    equations: [{ eq: 'FoM_W = P / ( 2^ENOB × f_s )', cap: 'Joules per conversion step' }],
    chart: 'walden',
    analogy: 'Litres per hundred kilometres for cars. It lets you compare a small hatchback with a lorry, because it divides out how much work each is doing.',
    example: { title: 'Is 300 mW good?', lines: [
      '12 bit, ENOB 11.5, 100 MSPS, 300 mW',
      'FoM = 0.3 / (2^11.5 × 1e8) = 1.04 pJ per step',
      'State of the art is a few femtojoules; 1 pJ is respectable for a fast part',
    ] },
    expert: 'Walden implicitly assumes power scales with 2^ENOB, which holds while the design is limited by comparator and switching energy. Once thermal noise dominates, power scales with 2^(2·ENOB) and the Schreier figure is the fairer comparison.',
  },
  {
    id: 'schreier', kind: 'param', part: 6, minutes: 2,
    title: 'Schreier figure of merit', symbol: 'FoM_S', unit: 'dB',
    what: 'The other way of asking the same question, built for converters whose limit is thermal noise rather than switching energy. Higher is better, and it is the figure used for precision and delta-sigma parts.',
    equations: [{ eq: 'FoM_S = SNDR + 10 log₁₀( BW / P )', cap: 'dB; add 10 log₁₀ of bandwidth per watt' }],
    chart: 'schreier',
    analogy: 'Rating a telescope by how faint a star it can see per unit of cost. It rewards sensitivity, not just size.',
    example: { title: 'The same part', lines: [
      'SNDR 70.5 dB, bandwidth 50 MHz, power 300 mW',
      'FoM_S = 70.5 + 10 log₁₀(5e7 / 0.3) = 152.7 dB',
      'Above about 175 dB is state of the art',
    ] },
    matters: 'Use Walden for fast, low-resolution parts and Schreier for slow, high-resolution ones. Quoting the wrong one flatters the wrong design.',
  },
  {
    id: 'crosstalk', kind: 'param', part: 6, minutes: 2,
    title: 'Crosstalk and channel isolation', symbol: '—', unit: 'dB',
    what: 'In a multi-channel converter, how much of a signal on one channel leaks into another. A large signal on channel 1 can put a ghost of itself on channel 2, where nothing was connected at all.',
    equations: [{ eq: 'crosstalk = 20 log₁₀( V_leaked / V_source )', cap: 'More negative is better; worsens with frequency' }],
    chart: 'crosstalk',
    analogy: 'Hearing next door’s television faintly through the wall. Nothing is wrong with your television; the isolation between rooms is finite.',
    example: { title: 'An 8-channel data logger', lines: [
      'Channel 1: 10 V thermocouple amplifier output',
      'Crosstalk −80 dB → 1 mV appears on channel 2',
      'On a 16-bit, 2 V range that is 33 LSB of pure fiction',
    ] },
    matters: 'Multiplexed converters also suffer settling crosstalk: the previous channel’s voltage has not fully decayed from the hold capacitor when the next is sampled.',
  },
  {
    id: 'iface', kind: 'param', part: 6, minutes: 2,
    title: 'Digital interface', symbol: '—', unit: '—',
    what: 'How the numbers leave the chip. The choice is set by the data rate: a slow part can use a handful of wires and a simple protocol, while a gigasample part needs serialised high-speed lanes.',
    chart: 'iface',
    bullets: [
      'SPI or I²C: a few hundred kSPS to a few MSPS, simplest wiring',
      'Parallel CMOS: fast but many pins, and the switching noise couples back into the analogue',
      'LVDS: differential, low noise, good to hundreds of MSPS',
      'JESD204B/C: serialised lanes with deterministic latency, for GSPS parts and synchronised arrays',
    ],
    analogy: 'The difference between handing over a note, posting a letter, and running a dedicated fibre. All deliver the message; they differ in how much you can send and how much fuss it is.',
    example: { title: 'Sizing the link', lines: [
      '12 bit at 250 MSPS = 3 Gbit/s of payload',
      'Too fast for parallel CMOS at sensible pin counts',
      'Two JESD204B lanes at 5 Gbit/s each, with 8b/10b overhead, carry it comfortably',
    ] },
    matters: 'Digital switching noise coupling back into the analogue front end is a real and common problem. It is one of the reasons LVDS and serialised interfaces won.',
  },

  /* ============================== Part 7 · Architectures and the datasheet */
  { id: 'sec7', kind: 'section', part: 7, subtitle: 'Which converter, and how to read its datasheet in the right order', notes: 'Bringing all the parameters together into a choice.' },
  {
    id: 'arch', kind: 'archtable', part: 7, minutes: 4,
    title: 'The five architectures compared',
    what: 'Every architecture is a different way of doing the quantise step, and each one trades the parameters in this talk against each other differently.',
    notes: 'Walk the table column by column. The point is that no architecture wins everywhere: the choice is which parameter you are willing to give up.',
  },
  {
    id: 'reading', kind: 'checklist', part: 7, minutes: 3,
    title: 'Reading a datasheet in the right order',
    what: 'Datasheets are written to flatter. Reading them in this order stops you being flattered.',
    notes: 'This is the practical takeaway slide. Encourage people to photograph it.',
  },
  {
    id: 'choose', kind: 'param', part: 7, minutes: 3,
    title: 'Worked example: choosing a converter', symbol: '—', unit: '—',
    what: 'A 20 MHz-wide radio channel at a 70 MHz intermediate frequency, needing 60 dB of usable dynamic range in a battery-powered product.',
    chart: 'choose',
    bullets: [
      'Sample rate: 20 MHz band → at least 44 MSPS; pick 61.44 MSPS and undersample the 70 MHz IF',
      'Analog bandwidth: must exceed 70 MHz comfortably — look for 300 MHz or more',
      'Resolution: 60 dB needed + 12 dB headroom + margin → 12 bits (74 dB ideal)',
      'ENOB at 70 MHz: must still be above 10.5 — check the curve, not the headline',
      'Jitter: 12 bits at 70 MHz needs about 450 fs total, clock included',
      'SFDR: at least 75 dB, because a strong neighbouring channel is guaranteed',
    ],
    analogy: 'Specifying a car by the journey rather than the brochure: how far, how fast, how much luggage, how much fuel.',
    example: { title: 'The numbers that decide it', lines: [
      'Jitter budget: 1/(2π × 70e6 × 10^(74/20)) = 455 fs',
      'FFT floor with a 4096-point transform: −74 − 33 = −107 dBFS',
      'Power target under 200 mW → FoM_W must beat about 0.7 pJ per step',
    ] },
    matters: 'Notice that resolution was decided fourth, not first. The frequency-dependent parameters did most of the work.',
  },
  {
    id: 'mistakes', kind: 'cards', part: 7, minutes: 3,
    title: 'Seven ways these parameters catch people out',
    notes: 'Each of these is a real, recurring failure. Invite the room to add their own.',
    cards: [
      ['1', 'Trusting resolution', 'A "16-bit" part delivering 12.5 ENOB at your frequency is a 12.5-bit part. Always read ENOB at the input frequency you will actually use.'],
      ['2', 'Comparing noise floors', 'Two FFT plots with different lengths are not comparable. Subtract 10 log₁₀(N/2) before you believe either of them.'],
      ['3', 'Ignoring the driver', 'Under-settling in the amplifier in front of the ADC appears in the FFT as distortion. The converter gets blamed for the driver’s sins.'],
      ['4', 'Jitter follows f_in', 'Undersampling a 200 MHz IF at 50 MSPS needs the jitter budget for 200 MHz, not 50 MHz. This surprises people constantly.'],
      ['5', 'Calibrating once', 'Room-temperature calibration removes offset and gain, and nothing at all of the drift that follows.'],
      ['6', 'THD with two signals', 'Single-tone distortion can look excellent while two-tone IMD is poor. Receivers must be specified on IMD.'],
      ['7', 'No headroom', 'Running close to full scale to "use all the bits" means the first signal peak clips and fills the spectrum with harmonics.'],
    ],
  },
  {
    id: 'cheatsheet', kind: 'cheatsheet', part: 7, minutes: 2,
    title: 'Every parameter on one slide',
    notes: 'The photograph slide. Leave it up during questions.',
  },
  {
    id: 'end', kind: 'end', part: 7, minutes: 1,
    title: 'Questions?',
    references: [
      'W. Kester (ed.), The Data Conversion Handbook, Analog Devices — the definitive reference',
      'W. Kester, "Understand SINAD, ENOB, SNR, THD, THD + N, and SFDR", Analog Devices MT-003',
      'IEEE Std 1241, Terminology and Test Methods for Analog-to-Digital Converters',
      'R. van de Plassche, CMOS Integrated Analog-to-Digital and Digital-to-Analog Converters',
      'B. Murmann, "ADC Performance Survey" — the running database behind both figures of merit',
    ],
  },
];

/* The families used by the parameter-map slide and the app's reference table. */
const FAMILIES = [
  { id: 'static', name: 'Static (DC)', when: 'Measuring slow or steady voltages',
    params: ['Resolution N', 'Full-scale range', 'LSB', 'Offset error', 'Gain error', 'DNL', 'INL', 'Missing codes', 'Monotonicity', 'TUE', 'Drift', 'PSRR', 'CMRR'] },
  { id: 'dynamic', name: 'Dynamic (AC)', when: 'Any signal that moves: radio, audio, vibration',
    params: ['SNR', 'THD', 'HD2 / HD3', 'SINAD', 'ENOB', 'SFDR', 'IMD', 'Input-referred noise', 'Noise-free bits', 'Dynamic range'] },
  { id: 'timing', name: 'Timing', when: 'Fast inputs, control loops, interleaving',
    params: ['Sample rate', 'Conversion time', 'Latency', 'Aperture delay', 'Aperture jitter', 'Acquisition time', 'Settling time', 'Slew rate', 'Overvoltage recovery'] },
  { id: 'bandwidth', name: 'Bandwidth', when: 'Undersampling, wideband or high-IF work',
    params: ['Analog bandwidth', 'Full-power bandwidth', 'Full-linear bandwidth', 'Oversampling ratio', 'Decimation'] },
  { id: 'system', name: 'Power and system', when: 'Budgets, board design, multi-channel',
    params: ['Power dissipation', 'Supply voltages', 'Walden FoM', 'Schreier FoM', 'Crosstalk', 'Output coding', 'Digital interface'] },
];

/* Architecture comparison, used by the deck table and the app. */
const ARCH = [
  ['Architecture', 'Speed', 'Resolution', 'Latency', 'Strength', 'Weakness'],
  ['Flash', 'GSPS', '4 – 8 bit', '1 cycle', 'Fastest possible; one clock per result', '2ᴺ−1 comparators: power and area explode'],
  ['SAR', 'kSPS – 100s MSPS', '8 – 18 bit', 'N cycles, no pipeline', 'Excellent power efficiency; zero latency', 'One result per N clocks'],
  ['Pipeline', '10s MSPS – GSPS', '10 – 16 bit', '8 – 16 cycles', 'Best speed-resolution product', 'Latency; needs calibration'],
  ['Delta-sigma', 'kSPS – 10s MSPS', '16 – 24 bit', 'Long (filter)', 'Superb DNL and dynamic range', 'Slow; heavy digital filtering'],
  ['Dual-slope', 'Hz – kSPS', '12 – 22 bit', 'Very long', 'Rejects mains hum inherently; very linear', 'Far too slow for signals'],
];

/* The one-slide cheat sheet: every parameter with its formula. */
const CHEATSHEET = [
  ['Resolution', 'levels = 2ᴺ;  LSB = FSR / 2ᴺ'],
  ['Quantisation', '−½ ≤ e_q < +½ LSB;  noise power = LSB²/12'],
  ['Offset / gain', 'shift of the staircase / wrong slope; both calibratable'],
  ['DNL', 'step width / LSB − 1;  ≤ −1 LSB means a missing code'],
  ['INL', 'Σ DNL;  sets the distortion floor, so it caps SFDR'],
  ['TUE', '√(E_O² + E_G² + INL² + …) for an uncalibrated system'],
  ['SNR', '6.02 N + 1.76 dB ideal;  harmonics excluded'],
  ['THD', '10 log₁₀(ΣP_harmonics / P_signal), in dBc'],
  ['SINAD', 'signal over noise + distortion together'],
  ['ENOB', '(SINAD − 1.76 + back-off) / 6.02'],
  ['SFDR', 'signal over the largest single spur, harmonic or not'],
  ['FFT floor', '−SNR − 10 log₁₀(N/2), so it moves with transform length'],
  ['Jitter', 'SNR = −20 log₁₀(2π f_in t_j);  uses input frequency'],
  ['Settling', 'ln(2^(N+1)) time constants to reach ½ LSB'],
  ['Slew needed', 'π × FSR × f for a full-scale sine'],
  ['Oversampling', '+10 log₁₀(OSR);  (6L+3) dB per doubling with L-th order shaping'],
  ['Walden FoM', 'P / (2^ENOB × f_s);  lower is better'],
  ['Schreier FoM', 'SNDR + 10 log₁₀(BW / P);  higher is better'],
];

/* The order to read a datasheet in. */
const CHECKLIST = [
  ['1', 'Sample rate and analog bandwidth', 'Can it reach your input frequency at all? Bandwidth must exceed the real input frequency, not just Nyquist.'],
  ['2', 'ENOB at your input frequency', 'Find the ENOB-versus-frequency curve. The headline resolution is the marketing number; this is the engineering one.'],
  ['3', 'SFDR at your input frequency', 'If a strong signal will sit near a weak one, this decides whether you can see the weak one.'],
  ['4', 'The jitter budget', 'Compute 1/(2π f_in × 10^(SNR/20)). If it is under a picosecond, your clock is now a major design problem.'],
  ['5', 'Driver and settling requirements', 'Track time divided by ln(2^(N+1)) gives the time constant your amplifier must achieve.'],
  ['6', 'Static specs, only if you measure DC', 'For AC work, offset and gain are irrelevant; INL still matters because it sets distortion.'],
  ['7', 'Power, latency and interface', 'The constraints that decide whether the part fits the product rather than the signal.'],
];

module.exports = { PARTS, SLIDES, FAMILIES, ARCH, CHEATSHEET, CHECKLIST };
